### ISSUE TITLE
Breaks when seconds is zero

### ISSUE THREAD

**Issue by zealias** [Tylous/Vibe#3]
**Error Trace:**

```
[+] Credentials valid, generating database
\Traceback (most recent call last):
  File "./vibe.py", line 468, in <module>
    l.main(args.IP, args.username, args.domain, args.password)
  File "/opt/Vibe/lib/AD.py", line 190, in main
    self.ADtime( time )
  File "/opt/Vibe/lib/AD.py", line 74, in ADtime
    date = dt.fromtimestamp(epoch)
ValueError: timestamp out of range for platform time_t
```

**Quick Fix in AD.py:**

```
def ADtime(self, time):
                global date
                seconds = int(time) / 10000000
                print "seconds: " + str(seconds)
                if seconds == 0:
                        epoch = 0
                else:
                        epoch = seconds - 11644473600
                print "epoch: " + str(epoch)
                dt = datetime.datetime(2000, 1, 1, 0, 0, 0)
                print "dt: " + str(dt)
                date = dt.fromtimestamp(epoch)
                print "date: " + str(date)
```

**Print:**
```
[+] Credentials valid, generating database
seconds: 13011398309
epoch: 1366924709
dt: 2000-01-01 00:00:00
date: 2013-04-25 21:18:29
...
seconds: 0
epoch: 0
dt: 2000-01-01 00:00:00
date: 1970-01-01 00:00:00
seconds: 0
epoch: 0
dt: 2000-01-01 00:00:00
date: 1970-01-01 00:00:00
seconds: 0
epoch: 0
dt: 2000-01-01 00:00:00
date: 1970-01-01 00:00:00
seconds: 13116627796
epoch: 1472154196
dt: 2000-01-01 00:00:00
date: 2016-08-25 19:43:16
```

**Comment by Tylous** [comment]
Thank you, I'll test this out tonight.

**Comment by Tylous** [comment]
Fixed
